#include "image.h"

void bxtk::core::bindImage(sol::state &lua) {
    lua.new_usertype<bxtk::core::Image>("Image",
        "new", sol::factories(
            []() { return new bxtk::core::Image(); }
        ),
        sol::base_classes, sol::bases<bxtk::core::BaseObject, bxtk::core::Resource>(),
        "adjustBcs", &bxtk::core::Image::adjustBcs,
        "blendRect", &bxtk::core::Image::blendRect,
        "blendRectMask", &bxtk::core::Image::blendRectMask,
        "blitRect", &bxtk::core::Image::blitRect,
        "blitRectMask", &bxtk::core::Image::blitRectMask,
        "crop", &bxtk::core::Image::crop,
        //"cropRect", &bxtk::core::Image::cropRect,
        "flipX", &bxtk::core::Image::flipX,
        "flipY", &bxtk::core::Image::flipY,
        "generateMipmaps", &bxtk::core::Image::generateMipmaps,
        "getData", &bxtk::core::Image::getData,
        "getDataSize", &bxtk::core::Image::getDataSize,
        "getFormat", &bxtk::core::Image::getFormat,
        "getHeight", &bxtk::core::Image::getHeight,
        "getMipmapCount", &bxtk::core::Image::getMipmapCount,
        "getMipmapOffset", &bxtk::core::Image::getMipmapOffset,
        "getPixel", &bxtk::core::Image::getPixel,
        "getPixelv", &bxtk::core::Image::getPixelv,
        "getRegion", &bxtk::core::Image::getRegion,
        "getSize", &bxtk::core::Image::getSize,
        "getUsedRect", &bxtk::core::Image::getUsedRect,
        "getWidth", &bxtk::core::Image::getWidth,
        "hasMipmaps", &bxtk::core::Image::hasMipmaps,
        "isCompressed", &bxtk::core::Image::isCompressed,
        "isEmpty", &bxtk::core::Image::isEmpty,
        "isInvisible", &bxtk::core::Image::isInvisible,
        "load", &bxtk::core::Image::load,
        "loadBmpFromBuffer", &bxtk::core::Image::loadBmpFromBuffer,
        "loadFromFile", &bxtk::core::Image::loadFromFile,
        "loadJpegFromBuffer", &bxtk::core::Image::loadJpegFromBuffer,
        "loadKtxFromBuffer", &bxtk::core::Image::loadKtxFromBuffer,
        "loadPngFromBuffer", &bxtk::core::Image::loadPngFromBuffer,
        "loadSvgFromBuffer", &bxtk::core::Image::loadSvgFromBuffer,
        "loadSvgFromString", &bxtk::core::Image::loadSvgFromString,
        "loadTgaFromBuffer", &bxtk::core::Image::loadTgaFromBuffer,
        "loadWebpFromBuffer", &bxtk::core::Image::loadWebpFromBuffer,
        "normalMapToXY", &bxtk::core::Image::normalMapToXY,
        "premultiplyAlpha", &bxtk::core::Image::premultiplyAlpha,
        "resize", &bxtk::core::Image::resize,
        "resizeToPo2", &bxtk::core::Image::resizeToPo2,
        "rotate90", &bxtk::core::Image::rotate90,
        "rotate180", &bxtk::core::Image::rotate180,
        "saveRxr", &bxtk::core::Image::saveRxr,
        "saveRxrToBuffer", &bxtk::core::Image::saveRxrToBuffer,
        "saveJpeg", &bxtk::core::Image::saveJpeg,
        "saveJpegToBuffer", &bxtk::core::Image::saveJpegToBuffer,
        "savePng", &bxtk::core::Image::savePng,
        "savePngToBuffer", &bxtk::core::Image::savePngToBuffer,
        "saveWebp", &bxtk::core::Image::saveWebp,
        "saveWebpToBuffer", &bxtk::core::Image::saveWebpToBuffer,
        //"setData", &bxtk::core::Image::setData,
        "setPixel", &bxtk::core::Image::setPixel,
        "setPixelv", &bxtk::core::Image::setPixelv,
        "shrinkX2", &bxtk::core::Image::shrinkX2,
        "srgbToLinear", &bxtk::core::Image::srgbToLinear,
        "cast", [](Resource* instance) {
            return new Image(godot::Object::cast_to<GodotImage>(instance->getResource()));
        }
    );
}